Example script
quentinv72/cs-catalog-api-client pull request #8
Opened 2021-02-04 22:00 UTC by soroushfall

Add examples to demonstrate usage of the Catalog API Client

2021-02-05 21:53 UTC, uchenna-cshop approved these changes
Good examples! LGTM

2021-02-08 15:48 UTC, quentinv72 requested changes

2021-02-08 15:48 UTC, quentinv72 commented on examples/constants.py
> +SKU_SOURCE = "us2-test-source"
I think this file should be called `data.py` or `mock_data.py`

2021-02-08 15:48 UTC, quentinv72 commented on examples/example_01_get_source_uuid.py
> +def get_source_uuid(sku_source):
This function shoudl return the `source_uuid` if it exists.
Also you should add type hinting.
`-> Optional[str]`

2021-02-08 15:48 UTC, quentinv72 commented on examples/example_01_get_source_uuid.py
> +def get_source_uuid(sku_source):
Also the client should be passed as an argument.

2021-02-08 15:50 UTC, quentinv72 commented
It would be better if the methods returned something and didn't just print. That way it'll be closer to how we will use it in our integrations.

2021-02-09 13:24 UTC, soroushfall commented on examples/example_01_get_source_uuid.py
> +def get_source_uuid(sku_source):
👍

2021-02-09 13:24 UTC, soroushfall commented on examples/constants.py
> +SKU_SOURCE = "us2-test-source"
👍

2021-03-31 13:22 UTC, closed without merging